"""remove_column_binary_and_add_column_url_in_cities_table

Revision ID: 375b66a04481
Revises: 16ef2c132fc5
Create Date: 2023-03-05 21:31:01.791610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "375b66a04481"
down_revision = "16ef2c132fc5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("url", mysql.VARCHAR(length=512), nullable=False))
    op.drop_column("images", "updated_at")
    op.drop_column("images", "binary")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("binary", sa.BLOB(), nullable=False))
    op.add_column("images", sa.Column("updated_at", mysql.DATETIME(), nullable=True))
    op.drop_column("images", "url")
    # ### end Alembic commands ###
