"""add_column_pricce_in_properties_table

Revision ID: 99ef78288eac
Revises: cebc1b41a423
Create Date: 2023-03-29 22:24:07.956023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99ef78288eac"
down_revision = "cebc1b41a423"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("properties", sa.Column("price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "price")
    # ### end Alembic commands ###
