"""create_table_addresses

Revision ID: c6e796b29285
Revises: d1ac6eb2881c
Create Date: 2023-02-27 22:36:31.332864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c6e796b29285"
down_revision = "d1ac6eb2881c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("street_name", mysql.VARCHAR(length=512), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("number", mysql.VARCHAR(length=45), nullable=True),
        sa.Column("cep", mysql.VARCHAR(length=45), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_id"), "addresses", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_addresses_id"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
