"""create_table_images_with_relationship

Revision ID: ca2996f50bb8
Revises: 95009367700f
Create Date: 2023-02-26 10:39:54.159868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca2996f50bb8"
down_revision = "95009367700f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("binary", sa.LargeBinary(), nullable=False),
        sa.Column("property_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "properties",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column("properties", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_properties_id"), "properties", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_id"), table_name="properties")
    op.drop_column("properties", "updated_at")
    op.drop_column("properties", "created_at")
    op.drop_table("images")
    # ### end Alembic commands ###
