"""create_columns_address_id_type_action_in_properties_table

Revision ID: 16ef2c132fc5
Revises: ddec959c5684
Create Date: 2023-03-02 22:32:58.960863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "16ef2c132fc5"
down_revision = "ddec959c5684"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column("images", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "updated_at")
    op.drop_column("images", "created_at")
    # ### end Alembic commands ###
