"""create_columns_address_id_type_action_in_properties_table

Revision ID: ddec959c5684
Revises: c6e796b29285
Create Date: 2023-02-27 22:42:06.278508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ddec959c5684"
down_revision = "c6e796b29285"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties", sa.Column("action", mysql.VARCHAR(length=45), nullable=True)
    )
    op.add_column(
        "properties", sa.Column("type", mysql.VARCHAR(length=45), nullable=True)
    )
    op.add_column("properties", sa.Column("address_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "properties", "addresses", ["address_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "properties", type_="foreignkey")
    op.drop_column("properties", "address_id")
    op.drop_column("properties", "type")
    op.drop_column("properties", "action")
    # ### end Alembic commands ###
