# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY ./requirements.txt /app/requirements.txt

# Install the required packages
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copy the rest of the application code and GitHub Actions into the container at /app
COPY . .


# Set environment variables from .env file
RUN set -o allexport; source REAL-STATE-API/api/.env; set +o allexport

# Expose port 5000 for the FastAPI app
EXPOSE 5000:5000

# Start the FastAPI app and MySQL instance
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port=5000"]
